site_name: !ENV [SITE_NAME, "My Learning Notes"]
site_url: https://hektorwang@github.io
site_description: Niko's Learning Notes
site_author: You-Know-Who

repo_name: GitHub
repo_url: https://github.com/Hektorwang/hektorwang.github.io
edit_uri: blob/main/docs/
remote_branch: gh-pages

nav:
  - Home: index.md
  # - About: about.md
  - Linux:
      - ssh: Linux/ssh.md
      - curl: Linux/curl.md
      - aria2: Linux/aria2.md
      - ansible: Linux/ansible.md
  - Bash:
      - blank: Bash/blank.md
  - Python:
      - pandas: Python/pandas.md
      - requests: Python/requests.md
  - Docker:
      - docker: Docker/docker.md
      - compose: Docker/compose.md
  - K8S:
      - blank: K8S/blank.md
  - Blog:
    - blog/index.md
  # - License: https://creativecommons.org/licenses/by-sa/4.0/
strict: true
markdown_extensions:
  - smarty
  - nl2br
  - md_in_html
  - toc:
      permalink: true
copyright: <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
theme:
  # name: mkdocs
  # name: readthedocs
  name: material
  # locale: zh_CN
  # locale: en
  # language: zh
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.footer
  # highlightjs: true
  # hljs_languages:
  #   - yaml
  #   - rust
  #   - bash
  #   - python
  #   - javascript
  #   - vue
  #   - django
  # include_homepage_in_sidebar: false
  # static_templates:
  #   - sitemap.html
  # include_sidebar: false
  # analytics:
  #   gtag: G-ABC123
  custom_dir: overrides/
plugins:
  - offline
  - blog
extra:
  generator: false
# extra_css:
#   - css/extra.css
#   - css/second_extra.css
# extra_javascript:
#   - some_plain_javascript.js       # <script src="some_plain_javascript.js"></script>
#         # New behavior in MkDocs 1.5:
#   - implicitly_as_module.mjs       # <script src="implicitly_as_module.mjs" type="module"></script>
#         # Config keys only supported since MkDocs 1.5:
#   - path: explicitly_as_module.mjs # <script src="explicitly_as_module.mjs" type="module"></script>
#     type: module
#   - path: deferred_plain.js        # <script src="deferred_plain.js" defer></script>
#     defer: true
#   - path: scripts/async_module.mjs # <script src="scripts/async_module.mjs" type="module" async></script>
#     type: module
#     async: true
# exclude_docs: |
#   api-config.json    # A file with this name anywhere.
#   /requirements.txt  # Top-level "docs/requirements.txt".
#   *.py               # Any file with this extension anywhere.
#   !/foo/example.py   # But keep this particular file.
