services:
  cloudbeaver-ee:
    image: dbeaver/cloudbeaver:24.2.3
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8080:8978"
    volumes:
      - ./workspace:/opt/cloudbeaver/workspace
    environment:
      - CLOUDBEAVER_PORT=8080