services:
  web:
    # image: nginx:latest
    image: openresty/openresty:alpine-fat
    container_name: web
    restart: unless-stopped # on-failure
    ports:
      - 'web_port:web_port'
    volumes:
      - ./conf.d:/etc/nginx/conf.d/:ro
      - ./default.d/:/etc/nginx/default.d/:ro
      - ./favicon.ico:/usr/local/openresty/nginx/html/favicon.ico:ro
      - ./log:/var/log/nginx/:rw
      - jenkins-data:/var/jenkins_home
    networks:
      - gitea_network
      - jenkins

networks:
  jenkins:
    external: true
    driver: bridge
  gitea_network:
    external: true
    driver: bridge
volumes:
  jenkins-data:
    external: true
