services:
  openresty:
    image: openresty/openresty:alpine-fat
    container_name: openresty
    restart: unless-stopped # on-failure
    shm_size: 256mb
    ports:
      - '443:443'
    volumes:
      - ./nginx_server.conf:/etc/nginx/conf.d/default.conf
      - ./favicon.ico:/usr/local/openresty/nginx/html/favicon.ico:ro
      - ./log:/var/log/nginx:rw
    networks:
      - gitea_network

networks:
  gitea_network:
    external: true
    driver: bridge
