services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped # on-failure
    shm_size: 256mb
    networks:
      - postgres_network
    volumes:
      - ./PGDATA:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=<POSTGRES_PASSWORD> # Change Password Here

networks:
  postgres_network:
    external: true
    driver: bridge
